### ISSUE TITLE
open in NEW window

### ISSUE THREAD

**Issue by 150d** [kyuucr/open-link-in-other-window#4]
Would it be possible to open a link not in an existing, but in a new window? 

Also, could there be separate options to open this new window in the foreground or in the background?

Regards

**Comment by kyuucr** [comment]
>Would it be possible to open a link not in an existing, but in a new window?

Wouldn't that just be the usual open link in new window? Firefox already have that by default, and I don't plan to extend it.

**Comment by 150d** [comment]
No, Firefox does not allow to "open in background" by default. For Firefox v58 there was a plugin ("open link in..."), but this doesn't work anymore with v60.

**Comment by kyuucr** [comment]
Yeah, I get it, but the scope of the plugin is opening link on other window for simplicity of maintaining it. If I would to implement that, it would be called "Open link in new background window" lol

**Comment by grahamperrin** [comment]
> … For Firefox v58 there was a plugin ("open link in..."), but this doesn't work anymore with v60. …

@150d please, do you have an address for that add-on? 

No exact match at https://addons.mozilla.org/search/?q=open%20link%20in&type=extension … maybe it was removed.

**Comment by 150d** [comment]
@grahamperrin No, I'm afraid I don't. I removed it after it stopped working with Firefox v6x, and didn't even keep a copy myself. :-(

There are plugins available to open in background _tabs_, but not in background windows... :-(
